pipeline:
  clone:
    image: plugins/git
    tags: true
  build:
    image: node:6.9.2
    commands:
      - cd apireceiver ; npm install
  docker:
    image: plugins/docker
    username: cp2017
    password: $DOCKER_PASSWORD
    repo: cp2017/apireceiver
    context: apireceiver
    dockerfile: apireceiver/Dockerfile
    tags:
     - latest
     - ${DRONE_BUILD_NUMBER}
  docker:
    image: plugins/docker
    username: cp2017
    password: $DOCKER_PASSWORD
    repo: cp2017/apisender
    context: apisender
    dockerfile: apisender/Dockerfile
    tags:
     - latest
     - ${DRONE_BUILD_NUMBER}
